const projects = [
  {
    id: 0,
    title: "",
    image: "",
    description: "",
    update: "",
    github: "",
    projectLink: "",
    portfolioLink: "",
    preview: "",
    tags: [],
    gallery: [],
    icon: "pe-7s-notebook",
    date: "",
  },
  {
    id: 1,
    title: "US Senate Chamber",
    image: "./assets/images/portfolioPics/us-senate-2.jpg",
    description: "The 2017 update of the system features a number of custom audio interface units using Dante AOIP technology. In keeping with the historic and traditional look of the chamber, all of this high-tech backend is made to interface with existing infrastructure using even more custom made hardware/furniture/speakers. My involvement also included design of the UI and programming the communications protocol of the audio control system using QSYS.",
    brief: "An audio and control system rework of the US Senate Chamber.",
    update: "Last updated August 2017",
    github: "",
    projectLink: "",
    portfolioLink: "",
    preview: "",
    tags: ["av", "audio"],
    gallery: [],
    icon: "",
    date: "",
  },
  {
    id: 2,
    title: "Tippet Rise Art Center",
    image: "./assets/images/portfolioPics/tippetRise_01.jpg",
    description: "Featured in Wired Magazine, I'm proud to have worked on the audiovisual system for the Tippet Rise Art Center. This system was designed on the back of a QSYS and AMX/SVSI framework and featured multichannel recording and playback.",
    brief: "Audio and control system designed for a performing arts center.",
    update: "Last updated June 2017",
    github: "",
    projectLink: "",
    portfolioLink: "",
    preview: "",
    tags: ["av", "audio"],
    gallery: [],
    icon: "",
    date: "",
  },
  {
    id: 3,
    title: "Red Rocks Audio Monitoring System",
    image: "./assets/images/portfolioPics/tippetRise_01.jpg",
    description: "Over the summer of 2016 I acted as the liason for the company designing the Red Rocks Amphitheatre audio monitoring system while it was being commissioned. This project was an absolute blast to work on and provided a lot of great experience leveraging technology to provide solutions to practical problems within society. The productions for each show I attended weren't too shabby, either!",
    brief: "Audio and control system designed for a performing arts center.",
    update: "Last updated June 2017",
    github: "",
    projectLink: "",
    portfolioLink: "",
    preview: "",
    tags: ["av", "audio"],
    gallery: [],
    icon: "",
    date: "",
  },
  
 
];

export default projects;