const projects = [
  {
    id: 0,
    title: "",
    image: "",
    description: "",
    update: "",
    github: "",
    projectLink: "",
    portfolioLink: "",
    preview: "",
    tags: [],
    gallery: [],
    icon: "pe-7s-notebook",
    date: "",
  },
  {
    id: 1,
    title: "US Senate Chamber",
    image: "./assets/images/portfolioPics/us-senate-2.jpg",
    description: "The 2017 update of the system features a number of custom audio interface units using Dante AOIP technology. In keeping with the historic and traditional look of the chamber, all of this high-tech backend is made to interface with existing infrastructure using even more custom made hardware/furniture/speakers. My involvement also included design of the UI and programming the communications protocol of the audio control system using QSYS.",
    update: "Last updated August 2017",
    github: "",
    projectLink: "",
    portfolioLink: "",
    preview: "",
    tags: ["av", "audio", "programming"],
    gallery: [],
    icon: "",
    date: "",
  },
  {
    id: 2,
    title: "cjko-test",
    image: "./assets/images/processing/jumbo-4.png",
    description: "lorem ipsum and some other odd garbage",
    update: "",
    github: "",
    projectLink: "",
    portfolioLink: "",
    preview: "",
    tags: ["webdev"],
    gallery: [],
    icon: "pe-7s-notebook",
  },
 
];

export default projects;